# Generated by Django 2.2.3 on 2020-06-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='item_price',
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kindpng.com%2Fimgv%2FiihmoJi_alt-text-placeholder-convenience-food-hd-png-download%2F&psig=AOvVaw3ViaIaNNPhQKIv_wTyXYr3&ust=1591531574820000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLCkw7CT7ekCFQAAAAAdAAAAABAF', max_length=1000),
        ),
    ]
